/**
 * Active match for the Conclave board.
 *
 * Prefers a real, on-chain match (match-live.json, written by
 * scripts/run-match.mts: every line generated by a deployed agent via
 * call_agent, signed under the standard model). Falls back to the
 * hand-authored EXHIBITION when no live match is present.
 */
import { EXHIBITION, type ExhibitionMatch } from "./exhibition";
import live from "./match-live.json";

const liveMatch = live as unknown as ExhibitionMatch;
export const IS_LIVE = Array.isArray(liveMatch?.rounds) && liveMatch.rounds.length > 0;
export const ACTIVE: ExhibitionMatch = IS_LIVE ? liveMatch : EXHIBITION;
